/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.util.ArrayList;
import java.util.List;
/**
 *
 * @author User
 */
public class NewJDialog extends javax.swing.JDialog {
    boolean a1 = true;
    int numl = 0;
    int a2 = 0;
    String b3 = "";  
    String c4 = "";
    String str = "";
    
    String[] wordList = {"Which animal features in the logo for Lamborghini?","What was the original color for all Ferrari models?","Which sports car features in the Back To The Future trilogy?",
        "Japanese car company Toyota was originally established as a textiles manufacturer. True or false?","What is the car driven by Mr Bean, the hapless character played by Rowan Atkinson?"," Who bought Rolls Royce in 1998?",
        "How many rings are in the Audi logo?","What geometric shape is generally used for stop signs?","What is the name of the biggest technology company in South Korea?","Which animal can be seen on the Porsche logo?","What is the rarest M&M color?",
        "What is the common name for dried plums?","Which country consumes the most chocolate per capita?","What was the first soft drink in space?","Which is the only edible food that never goes bad?"
    };
    String[] ans = {"bull","red","delorean","true","mini","bmw","four","Octagon","Samsung","Horse","brown","Prunes","Switzerland","coke","honey"};
    
    
    /**
     * Creates new form NewJDialog
     */
    public NewJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        re = new javax.swing.JButton();
        face = new javax.swing.JLabel();
        head = new javax.swing.JLabel();
        body = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnNewWord = new javax.swing.JButton();
        undersocre = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblPoint = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        re.setIcon(new javax.swing.ImageIcon("C:\\Users\\pupab0551\\Downloads\\Untitled drawing (4).png")); // NOI18N
        re.setText("jButton2");
        re.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reActionPerformed(evt);
            }
        });
        jPanel1.add(re, new org.netbeans.lib.awtextra.AbsoluteConstraints(3, 3, 830, 700));
        re.setVisible(false);

        face.setIcon(new javax.swing.ImageIcon("C:\\Users\\pupab0551\\Downloads\\Untitled drawing (3).png")); // NOI18N
        jPanel1.add(face, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 270, -1, -1));
        face.setVisible(false);

        head.setIcon(new javax.swing.ImageIcon("C:\\Users\\pupab0551\\Downloads\\Untitled drawing (1).png")); // NOI18N
        jPanel1.add(head, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 240, -1, -1));
        head.setVisible(false);

        body.setIcon(new javax.swing.ImageIcon("C:\\Users\\pupab0551\\Downloads\\Untitled drawing (2).png")); // NOI18N
        jPanel1.add(body, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 320, -1, 130));
        body.setVisible(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("HANGMAN OF DOOM!!!!");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 470, 41));

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 213, 104, 41));

        jButton1.setText("Submit ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(632, 222, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 51));
        jLabel3.setText("Question ");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 114, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 0, 51));
        jLabel4.setText("Your Guess");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(518, 193, -1, -1));

        btnNewWord.setText("New question ");
        btnNewWord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewWordActionPerformed(evt);
            }
        });
        jPanel1.add(btnNewWord, new org.netbeans.lib.awtextra.AbsoluteConstraints(616, 110, -1, -1));
        jPanel1.add(undersocre, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 144, 365, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\pupab0551\\Downloads\\Untitled drawing.png")); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 235, -1, -1));
        jLabel2.setVisible(false);

        lblPoint.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblPoint.setForeground(new java.awt.Color(255, 255, 255));
        lblPoint.setText("POINT : 0");
        jPanel1.add(lblPoint, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 67, 90, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 51));
        jLabel5.setText("Guess the correct answer to the questions!!");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 310, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed
        String text = "";
        String answer = "";
    private void btnNewWordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewWordActionPerformed
        // TODO add your handling code here:
        
        
        int x = (int) (Math.random() * 15 +1); 
        text += wordList[x];
        answer = ans[x];
        jLabel3.setText(text);
        for (int i = 1; i <= text.length(); i++){
        numl++;
            
        }
        ;  
        undersocre.setText(String.valueOf ("your word has "+ answer.length()+" letters")  );
        numl = 0;
        
        text = "";
        
        
    }//GEN-LAST:event_btnNewWordActionPerformed
        String word = "";
        int point = 0;
        int counter = 0;
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String letter = jTextField1.getText();
       
        if (letter.toLowerCase().equals(answer)) {
            point++;
        int x = (int) (Math.random() * 15 +1);
        text += wordList[x];
        answer = ans[x];
        jLabel3.setText(text);
        for (int i = 1; i <= text.length(); i++){
        numl++;
        text = "";
        }
        ;  
        undersocre.setText(String.valueOf ("your word has "+ answer.length()+" letters")  );
        numl = 0;
        
        
        
            lblPoint.setText("POINT : " + point);
            jTextField1.setText("");
        
        
       
        
        }
        else {
            counter++;
            if (counter == 1)
            {
                jLabel2.setVisible(true);
            }      
            if (counter == 2) {
                head.setVisible(true);
            }
            if (counter == 3) {
                body.setVisible(true);
            }
            if (counter == 4 ){
                face.setVisible(true);
            }
            if (counter > 4){
                re.setVisible(true);
            }
        }
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void reActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reActionPerformed
    counter = 0;
    point = 0;
    jLabel2.setVisible(false);
    head.setVisible(false);
    body.setVisible(false);
    face.setVisible(false);
    re.setVisible(false);
    
    }//GEN-LAST:event_reActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                NewJDialog dialog = new NewJDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel body;
    private javax.swing.JButton btnNewWord;
    private javax.swing.JLabel face;
    private javax.swing.JLabel head;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lblPoint;
    private javax.swing.JButton re;
    private javax.swing.JLabel undersocre;
    // End of variables declaration//GEN-END:variables
}
